### ISSUE TITLE
Having trouble with secrets.toml

### ISSUE THREAD

**Issue by yuickey** [fedebotu/k-trains#11]
I have cloned your git and ran it, it keep asking password(which is email password i guess). I've already wrote file "secrets.toml" in .streamlit directory. 

So I tried upload entire script to GitHub and connect with Streamlit and set secret variables in advanced settings but no luck..

Can you guide this situation? 

Thanks for great and neat work by the way.

**Comment by yuickey** [comment]
Now I figured out. I needed to set the "app password" at Google side. Now it works like charm. 
I would like to know if the ticket is currently sold out, and I run the app, will it continue to try to get the ticket? Isn't there a limit ?

**Comment by fedebotu** [comment]
It will continuously try to get the ticket! We found no limit so far; the script should run until the train departs and it is not available anymore
