### ISSUE TITLE
Having trouble with KTX Login

### ISSUE THREAD

**Issue by wkdwnghwkd** [fedebotu/k-trains#13]
Hello,

First of all, thank you for making this web site.
I really love this.

By the way, I'm having trouble with KTX Login System.
I can login in Korail web site and App, but I can't login in this macro web site.

I even can't find any clue for this bug in Devtools.

I hope you guys figure it out.

**Comment by fedebotu** [comment]
Hi! 

Are you logging in with the [deployed Streamlit app](https://k-trains.streamlit.app/) or with a local instance?
I noticed that recently the app has been receiving too much traffic, so the Streamlit servers sometimes block too many requests to the same website (e.g., Korail / SRT).
(Also , Note that this is not a "macro", but an actual deployed website with a bot that runs on a separate computer somewhere in the USA)

Could you try with a local instance and see if you can log in?

**Comment by wkdwnghwkd** [comment]
Thank you for your prompt reply.

I'm logging in with the deployed Streamlit app.

I feel sorry that I guess I contributed to making too much traffic. When I noticed that my login session is gone, I kept trying to make another request for reservation. That's because i felt like my request is already disconnected. Now I know that it was bad behavior for server.

Okay! I will let you know after trying with a local instance!

Thank you

**Comment by fedebotu** [comment]
Don't worry, luckily this is a free service from Streamlit. We were not expecting this many users :sweat_smile:

**Comment by GeunSam2** [comment]
I think this login issue is not only abot lot of traffic.
There is some changed at korail api spec.
check this issue https://github.com/carpedm20/korail2/issues/47#issuecomment-1969414155

**Comment by fedebotu** [comment]
That is why then! If you have some time @GeunSam2 , please keep us updated and in case contribute~
(CC @cecy07 )
