### ISSUE TITLE
check the issue with function

### ISSUE THREAD

**Issue by wkdwnghwkd** [fedebotu/k-trains#9]
Hello, 

I found a bug to fix while trying to get a ticket for KTX.

I guess some function doesn't fit with multi language environment(I used Korean tho).
I don't have any authority for checking the exact situation but i do know that i can macro when i use this tool in English.

![image](https://github.com/fedebotu/k-trains/assets/41713593/f99a8422-fc40-4b0d-9b75-d039e3730837)

I hope this issue works for you.

Thank you.

**Comment by fedebotu** [comment]
Hi, thanks for reporting! I believe this is due `pandas` not finding the train code when there is a translation. 
Just to clarify, you confirm it does work when trying in English?

PS: maybe @cecy07 knows something more ;)
